---
# handlers file for sbaerlocher.common

- name: enable fstrim
  become: true
  service: name=fstrim.timer state=enable

- name: Reboot server
  shell: shutdown -r now
  async: 1
  poll: 0
  ignore_errors: true

- name: Pause for 10 seconds
  pause:
    seconds: 10

- name: Wait for reboot
  wait_for_connection:
        timeout: 300
